version: '3.8'

services:
    mlflow-nginx:
        restart: unless-stopped
        image: nginx:1.21.5
        container_name: mlflow-nginx
        ports:
            - "80:80"
        networks:
            - frontend
        volumes:
            - /etc/apache2:/etc/nginx/passwords
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - mlflow-server

    mlflow-db:
        restart: unless-stopped
        image: postgres:9.6.24
        container_name: mlflow-db
        expose:
            - "5432"
        networks:
            - backend
        volumes:
            - ./postgresql/db_data:/var/lib/postgresql/data
            - ./postgresql/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_MLFLOW_USER
            - POSTGRES_MLFLOW_PASSWORD
            - POSTGRES_MLFLOW_DB

    mlflow-server:
        restart: unless-stopped
        build: ./mlflow
        container_name: mlflow-server
        expose:
            - "5000"
        networks:
            - frontend
            - backend
        volumes:
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        command: bash -c "
            ssh-keyscan -H $MLFLOW_SFTP_HOST >> ~/.ssh/known_hosts
            && mlflow server --backend-store-uri postgresql+psycopg2://${POSTGRES_MLFLOW_USER}:${POSTGRES_MLFLOW_PASSWORD}@mlflow-db:5432/${POSTGRES_MLFLOW_DB} --default-artifact-root sftp://${MLFLOW_SFTP_USER}@${MLFLOW_SFTP_HOST}${MLFLOW_SFTP_ARTIFACTS_PATH} --host 0.0.0.0 --port 5000"
        depends_on:
            - mlflow-db

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
