version: '3.8'

services:
    mlflow-nginx:
        restart: unless-stopped
        image: nginx:1.21.5
        container_name: mlflow-nginx
        ports:
            - "80:80"
        networks:
            - frontend
        volumes:
            - /etc/apache2:/etc/nginx/passwords
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - mlflow-server

    mlflow-metada-db:
        restart: unless-stopped
        image: postgres:9.6.24
        container_name: mlflow-metada-db
        expose:
            - "5432"
        networks:
            - backend
        volumes:
            - ./postgresql/db_data:/var/lib/postgresql/data
            - ./postgresql/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_MLFLOW_USER
            - POSTGRES_MLFLOW_PASSWORD
            - POSTGRES_MLFLOW_DB

    mlflow-artifacts-storage:
        restart: unless-stopped
        image: minio/minio:RELEASE.2022-01-08T03-11-54Z
        container_name: mlflow-artifacts-storage
        ports:
            - "9000:9000"
            - "9001:9001"
        networks:
            - frontend
            - backend
        volumes:
            - ./minio/data:/data
        environment:
            - MINIO_ROOT_USER
            - MINIO_ROOT_PASSWORD
        command: server /data --console-address ":9001"

    mlflow-server:
        restart: unless-stopped
        build: ./mlflow
        container_name: mlflow-server
        expose:
            - "5000"
        networks:
            - frontend
            - backend
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://mlflow-artifacts-storage:9000
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
        command: mlflow server --backend-store-uri postgresql+psycopg2://${POSTGRES_MLFLOW_USER}:${POSTGRES_MLFLOW_PASSWORD}@mlflow-metada-db:5432/${POSTGRES_MLFLOW_DB} --default-artifact-root ${MLFLOW_ARTIFACTS_PATH} --host 0.0.0.0 --port 5000
        depends_on:
            - mlflow-metada-db
            - mlflow-artifacts-storage

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
