#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<-EOSQL
    CREATE USER $POSTGRES_MLFLOW_USER WITH ENCRYPTED PASSWORD '$POSTGRES_MLFLOW_PASSWORD';
    CREATE DATABASE $POSTGRES_MLFLOW_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_MLFLOW_DB TO $POSTGRES_MLFLOW_USER;
EOSQL